"""empty message

Revision ID: 081901dc4754
Revises: 7c18a2b6abb0
Create Date: 2020-08-25 20:53:17.472983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081901dc4754'
down_revision = '7c18a2b6abb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pro', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pro', type_='unique')
    # ### end Alembic commands ###
