"""empty message

Revision ID: 67d6f8903a9c
Revises: 2eeca2ba095f
Create Date: 2020-08-25 19:30:38.519268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d6f8903a9c'
down_revision = '2eeca2ba095f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pro')
    # ### end Alembic commands ###
