"""empty message

Revision ID: 7c18a2b6abb0
Revises: 67d6f8903a9c
Create Date: 2020-08-25 19:59:53.383727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c18a2b6abb0'
down_revision = '67d6f8903a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pro', sa.Column('name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pro', 'name')
    # ### end Alembic commands ###
