"""empty message

Revision ID: e594528b9e27
Revises: fdd27ceacc26
Create Date: 2020-08-26 21:20:43.735676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e594528b9e27'
down_revision = 'fdd27ceacc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pro', sa.Column('uname', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pro', 'uname')
    # ### end Alembic commands ###
