"""empty message

Revision ID: fdd27ceacc26
Revises: 452b89f3e9be
Create Date: 2020-08-26 20:59:21.462885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd27ceacc26'
down_revision = '452b89f3e9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('back',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=10), nullable=True),
    sa.Column('backwords', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('back')
    # ### end Alembic commands ###
